### ISSUE TITLE
Wrong programme description in "Manuals"

### ISSUE THREAD

**Issue by stranskj** [biosaxs-com/atsas-community#1927]
In manuals, there is duplication of programme description:
[datporod](https://biosaxs-com.github.io/atsas/4.0.0/manuals/datporod.html) - Determine the molecular weight from Porod Volume.
[datregrid](https://biosaxs-com.github.io/atsas/4.0.0/manuals/datregrid.html) - Determine the molecular weight from Porod Volume.

**Comment by franke-biosaxs** [comment]
[Updated](https://biosaxs-com.github.io/atsas/4.0.0/manuals/) - thanks for pointing it out!
