### ISSUE TITLE
Chromixs: "Calculate Structural Parameters" crashes

### ISSUE THREAD

**Issue by stranskj** [biosaxs-com/atsas-community#1932]
In Chromixs, when I try to use the button "Calculate Structural Parameters", while Buffer Frames and Sample frames selected, the program crashes with "Segmentation fault"
I expect it to calculate Rg & Mw as function of frame number,  since I have not find these elsewhere...
I got the same result in Windows and Linux edition.

**Comment by franke-biosaxs** [comment]
Hi Jan. Thanks for the report. I can not reproduce this with the data sets I have. Would you be able to either attach or send the data by email? Ideally with the saved project file with the selected frames, so all I have to do is load the project and click the button to reproduce? Cheers!

**Comment by I-G-E** [comment]
Hi has this problem been fixed? I have just installed 4.0.0-2 and have tried the 'calculate structural parameters' button to calculate Rg and MW on the selected frames but the GUI crashes. Is it advised to go back to ATSAS 3 if we want to export the curves showing the Rg values?
