### ISSUE TITLE
primus: rename 'Absolute Scale' plot to 'Linear Scale'

### ISSUE THREAD

**Issue by plmnnk** [biosaxs-com/atsas-community#1934]
In PRIMUS under 'Plot' the first plot is called 'Absolute Scale'. These are the same words that are used in e.g. Analysis > Molecular Weight > Concentration dependent. But the meaning is different - which causes confusion.
I suggest to rename this plot to 'Linear Scale'.

**Comment by franke-biosaxs** [comment]
Done for ATSAS-4.0.1. Closing.
