### ISSUE TITLE
primus: linear plots: horizontal I=0 line disappeared in 4.0

### ISSUE THREAD

**Issue by plmnnk** [biosaxs-com/atsas-community#1935]
In ATSAS 3.x in PRIMUS there was a horizontal line for I(s)=0. It didn't make much sense in the logarithmic plots but in the Absolute Scale, Kratky and Porod plots it was very helpful, e.g. when checking for oversubtraction. In ATSAS 4.0 this line is gone. It would be great to have it back for the plots mentioned above where I(s) is on the linear scale.

**Comment by franke-biosaxs** [comment]
You can add it back yourself: right click on the plot, select "Insert Annotation". Remove the placeholder text and set the position to (0,0). Select lines "horizontal". See here:

<img width="1354" alt="Screenshot 2024-08-28 at 10 22 07" src="https://github.com/user-attachments/assets/850ab611-ce99-4433-922c-030cf2fd3d97">

**Comment by plmnnk** [comment]
Thanks, good to know! Unfortunately, it disappears when PRIMUS is closed and opened again. It would be great to have it always visible in plots where the vertical axis is linear.

**Comment by franke-biosaxs** [comment]
That's what Projects are for? At least I think it should be saved together with a project. Re-open a project, your line is there. Start a new project, add a new line wherever needed. At least that was the idea.

**Comment by franke-biosaxs** [comment]
Al, do you agree to close this?

**Comment by plmnnk** [comment]
I think it would be best to have the horizontal line in linear plots by default.
Unfortunately, "Insert Annotation" to the linear plot at the position (0,0) makes the "Logarithmic Scale", "Double Logarithmic Scale" and "Guinier" plots unusable. To reproduce: 
- open any data (e.g. SASDDN3), 
- switch to the linear plot, 
- insert annotation as described above, 
- switch to the "Logarithmic Scale".

**Comment by franke-biosaxs** [comment]
Thanks for the report(s). I've added a horizontal marker line to the main plots in primus, sasplot and gnomplot. 

Further, as per [comment](https://github.com/biosaxs-com/atsas-community/issues/1935#issuecomment-2355572209), any annotation will now be hidden if the transformed coordinates are invalid. Most notably zero lines on linear plots when converted to log plot.

All of the above will be available as of 4.0.1.
