### ISSUE TITLE
UI sw ignores CLI path

### ISSUE THREAD

**Issue by stranskj** [biosaxs-com/atsas-community#1936]
When opened from command line, both Primus and Chromixs ignore path, from which they were opened in the "Open" dialogs. E.g. when I open Primus and want to open files to work with, the "Open" dialog opens in the $HOME folder. I would expect the path it was started from (as it used to be in the older versions).
Processed files are fine, even though, it is not super obvious, where they will end up (like when you do Subtraction, for example).

Observed in Ubuntu 22.04

**Comment by franke-biosaxs** [comment]
Thanks for the report. This will be changed to the original behaviour as of ASTAS-4.0.1. Closing.
