### ISSUE TITLE
primus: allow negative 'Background' values

### ISSUE THREAD

**Issue by plmnnk** [biosaxs-com/atsas-community#1937]
PRIMUS from ATSAS 4.0.0 on Windows: in the 'Documents' tab, one can enable the 'Background Constant Column'. However, the 'Background' value can only be positive. Negative values totally make sense here, please allow them (like it was in ATSAS 3.2).

**Comment by franke-biosaxs** [comment]
Done for ATSAS-4.0.1. Closing.
