### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by barbara551** [biosaxs-com/atsas-community#1938]
Hi, I installed ATSAS 4.0.0.2 on my PC (Win11), everything worked fine apparently but when I tried to use  Crysol, I had the following error: 
> crysol --prefix 6lyz --smax 0.5 --ns 501 --lm 20 --dns 0.334 C:/Program Files/ATSAS-4.0.0/doc/crysol/example/6lyz.pdb --shell directional --fb 17 --constant

error: unable to read input file:

the 6lyz.pdb is the one provided as an example with the installation so I assume this not the problem.... The same error happened with Primus.
Before installing the new version, I uninstalled the previous version of ATSAS  I had on my PC and also tried to install the V4.0.0.2 on a "clean" PC ( also Win11, ATSAS never installed before) to check this was not due to some issues on mine,  but had the same error. Any suggestion on how to solve this problem? thanks a lot for any help!
Barbara

**Comment by franke-biosaxs** [comment]
> > crysol --prefix 6lyz --smax 0.5 --ns 501 --lm 20 --dns 0.334 C:/Program Files/ATSAS-4.0.0/doc/crysol/example/6lyz.pdb --shell directional --fb 17 --constant
> 
> error: unable to read input file:

Please try and add quotes to the file path with whitespace, i.e. "C:/Program Files/ATSAS-4.0.0/doc/crysol/example/6lyz.pdb".

**Comment by franke-biosaxs** [comment]
Could you please let me know if the above helped you? If yes, we can close this issue, otherwise I would need more information. Thanks.

**Comment by franke-biosaxs** [comment]
Closing with the assumption that this has been resolved as indicated.
