### ISSUE TITLE
Installer 4.0.1-1

### ISSUE THREAD

**Issue by stranskj** [biosaxs-com/atsas-community#1952]
Few issues spotted while installing  latest release.
OS: Ubuntu 24.04 LTS
Installer: ATSAS-4.0.1-1-Linux-Ubuntu-24.run

1) When I forget the "install" command in CLI, I get following QT error. I suspect a windowed installer should pop-up?

`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal.

Aborted (core dumped)
`

After successful  installations, GUI applications (seem to) work.

2) Warnings in the installation log:
`[3] Retrieving information from remote repositories...
[195] Warning: Network error while downloading 'https://biosaxs.com//Updates.xml?3511526422': Error transferring https://biosaxs.com//Updates.xml?3511526422 - server replied: Not Found.
[195] Warning: Cannot fetch a valid version of Updates.xml from repository "": "Expected ' ', but got '>'."
`

**Comment by franke-biosaxs** [comment]
> 1. When I forget the "install" command in CLI, I get following QT error. I suspect a windowed installer should pop-up?

Probably. The Installer Framework is a third party tool, so not much we can do there.


> 2. Warnings in the installation log:
>    `[3] Retrieving information from remote repositories... [195] Warning: Network error while downloading 'https://biosaxs.com//Updates.xml?3511526422': Error transferring https://biosaxs.com//Updates.xml?3511526422 - server replied: Not Found. [195] Warning: Cannot fetch a valid version of Updates.xml from repository "": "Expected ' ', but got '>'." `

Said installer framework is (mostly) meant for online installs and update distribution. However, as you are aware, we only offer offline installers. Currently there is nothing for updates in place, but during setup of the offline installers I must give an URL to check for updates. The URL given does not exist (yet). If there is ever time and motivation to do so, I would like to set up the online updates.

Thanks for the reports. Unfortunately, there is nothing much I can do here at the moment. Closing again.
